dist: trusty
sudo: required
language: cpp
compiler: gcc

before_script:
  # Add repository for GCC 7
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

script:
  # Install GCC 7 and Boost Test Framework 1.54
- sudo apt-get install -y -qq g++-7 libboost-test1.54-dev
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Build, test and pack project.
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uithamsteri:$BINTRAY_API_KEY "https://api.bintray.com/content/hamsterisoft/apt-repo/ipfilter/0.0.$TRAVIS_BUILD_NUMBER/pool/main/i/ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
